### ISSUE TITLE
ParTool lag when I unpack decrypted chara

### ISSUE THREAD

**Issue by vairusan** [Kaplas80/ParManager#10]
I used YagamyDecriptionAgency for decryption chara.par, but PartTool freezes and cannot unpack it. What is it connected with?
![591](https://user-images.githubusercontent.com/117326021/199632014-823d717c-e477-451a-ad16-5f76e78f78be.png)

**Comment by Kaplas80** [comment]
I don't have Judgement games, so I can't test it. Maybe the decryption is not working.

Also, you are using an old Partool version, latest one is v1.3.3
