### ISSUE TITLE
texture missing

### ISSUE THREAD

**Issue by GreenZGit** [Kaplas80/ParManager#11]
i want to open characters or maps with blender , so i put them thrugh the par tool and textures are missing , i dont know why because i can texture the model myself but the textures are missing from the folder that comes out of the par tool, is there anyway i could solve this?

**Comment by Kaplas80** [comment]
I'm sorry, but I can't help you with that problem. Partool extracts all the files inside the `.par` archives. If there are no textures, probably, they are inside other archive.

You can try to ask in [yakuza modding discord server](https://discord.gg/yakuzamodding). I'm sure someone can help you.
