### ISSUE TITLE
Yakuza 3, 4, 5 boot_en.par

### ISSUE THREAD

**Issue by Darlaig23** [Kaplas80/ParManager#13]
Hello, I am currently working on a Spanish translation of the Yakuza saga games and several of the text files are located in the boot_en.par and wdr_en files. When I extract the files there is no problem, I edit the text files with the Hex Editor and I save them, the problem comes when I create the file again, for some reason the game does not read the files and crashes or remains on a black screen

I thought it might be a Hex Editor error but then I extract and create the file again without touch anything and the error happened the same way, I don't know if I'm doing something wrong or if it's a ParTool problem, I would really appreciate some help with this.

PS: Sorry for my bad english

**Comment by Kaplas80** [comment]
No te preocupes por tu inglés, te he entendido xD

No es problema del partool. Si traduces modificando los ficheros directamente usando un editor hexadecimal tienes que mantener la misma longitud de los textos originales, no pueden ser ni más largos ni más cortos. Si eso no se cumple, el juego no funcionará.

----

It is not a partool bug. If you edit the files with a hexadecimal editor, you have to keep the length of the text strings, neither longer nor shorter. If you do not meet this requirement, the game will not start.

**Comment by Darlaig23** [comment]
Thanks for responding so quickly :D

Yes, I know that, but the problem is that even if I extract and then recreate the .par file (Even if I don't modify anything) the game does not recognize it and throws an error (Can be a Black Screen, a Infinite Loading Screen or directly doesn't start an crash)  in the same way, as if it were not a file that the game could read, it only works with the original boot_en.par and wdr_en.par files of the game, in one of the posts I read that perhaps it could be due to a compression problem of the files within the same .par or something like that

I even tried simply changing a single letter in the game (That way "there shouldn't be a problem" I thought, since 99.99% of the text file was still the original) but the error still persists anyway

**Comment by Kaplas80** [comment]
What command are you using for extracting and repacking the files? Maybe you are using wrong parameters... Yakuza 3,4 and 5 PS3 games needed to use `--alternative-mode` flag.

**Comment by Darlaig23** [comment]
I am dragging the files and folders to ParToll, and the versions that I am translating are the PC Remastered ones, I was already able to translate the cinematics of the 3 games without problems since when I unpack the files the texts were in Excel files, but the idea is to translate the entire game (Or at least the main story)

**Comment by Darlaig23** [comment]
It's quite strange, because for example Yakuza Kiwami 2 and Yakuza 6 I could modify them without problems almost in their entirety (Even with the HexEd), but I suppose it doesn't have much to do with it because they are 2 different engines

**Comment by Kaplas80** [comment]
Dragging the folder to .exe will use the default options (type 1 compression and standard mode). I suggest you to try with `--alternative-mode`.

I don't have the game installed, so I can't try it out.

**Comment by Darlaig23** [comment]
Okay, I'll try to use that method to see if it works, I'll keep you informed of any news, and I'm sorry for this question but I'm quite new with these programs, but how do I put the tool in alternative mode?

**Comment by Kaplas80** [comment]
You have to run the app from command line or, if you are in Windows, you can create a `create-par.bat` file with this content:

```bat
C:\partool\ParTool.exe create C:\extract\boot_en.par.unpack C:\rebuild\boot_en.par --alternative-mode
```

You'll have to change `C:\partool` with the folder where you have ParTool installed, `C:\extract` with the folder where you have extracted the .par file and `C:\rebuild` with the folder where you want to place the new file.

**Comment by Darlaig23** [comment]
Okay, I figured out how to execute the command on the command line, but when I finish creating the file it shows me this error

Unhandled exception. System.UnauthorizedAccessException: Access to the path 'A:\TRADUCCIONES' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Yarhl.IO.StreamFormat.LazyFileStream.Initialize()
   at Yarhl.IO.StreamFormat.LazyFileStream.Write(Byte[] buffer, Int32 index, Int32 count)
   at Yarhl.IO.DataStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Yarhl.IO.DataWriter.Write(Byte[] buffer)
   at Yarhl.IO.DataWriter.Write(String text, Int32 fixedSize, String terminator, Encoding encoding)
   at Yarhl.IO.DataWriter.Write(String text, Int32 fixedSize, Boolean nullTerminator, Encoding encoding)
   at ParLibrary.Converter.ParArchiveWriter.Convert(NodeContainerFormat source)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Yarhl.FileFormat.ConvertFormat.With(IConverter converter, Object src)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Yarhl.FileFormat.ConvertFormat.With[TConv,TParam](TParam param, Object src)
   at Yarhl.FileSystem.Node.TransformWith[TConv,TParam](TParam param)
   at ParTool.Program.Create(Create opts)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at ParTool.Program.Main(String[] args)

**Comment by Darlaig23** [comment]
Nevermind, I Solved

**Comment by Darlaig23** [comment]
IT WORKS!!!!! I can't belive it! It took me 5 days this shit! Thank You So much! You're the best!

When the project is finished I will give you the well-deserved credits for helping me!

**Comment by Darlaig23** [comment]
IT WORKS!!!!! I can't belive it! This shit took me 5 days! Thank You So much! You're the best!

When the project is finished I will give you the well-deserved credits for helping me!
