### ISSUE TITLE
Application not working

### ISSUE THREAD

**Issue by ahmetenes120** [Kaplas80/ParManager#18]
When I enter the application, the CMD tab opens and after 1 second it closes again. I tried it on 2 different operating systems, I ran it as administrator.

**Comment by Kaplas80** [comment]
It is a command line app, you can't simply double click on it. You have to run it from command line or drag&drop a .par file over the executable to extract it.

**Comment by ahmetenes120** [comment]
> It is a command line app, you can't simply double click on it. You have to run it from command line or drag&drop a .par file over the executable to extract it.

Thanks.
