### ISSUE TITLE
Unable to unpack chara.par Judgment file.

### ISSUE THREAD

**Issue by SalemLockehart** [Kaplas80/ParManager#19]
I get this error when inputting this command to extract the chara.par file from Judgment: `.\ParTool.exe extract chara.par C:\Users\Jade\Desktop\ParTool\Judgment\chara [-r]`

![powershell_JeXZ20rcy7](https://github.com/Kaplas80/ParManager/assets/138178708/75a812bd-ecfd-407a-9486-f00fe8242638)

It also happens with drag and drop. It doesn't happen with other .par files I've tried.

**Comment by Kaplas80** [comment]
Duplicated. See #8
