### ISSUE TITLE
ParTool 1.3.0 error

### ISSUE THREAD

**Issue by Vanillepanda** [Kaplas80/ParManager#2]
Hello @Kaplas80 & @SutandoTsukai181 !

I tried to run the ParManager becaues i want to extract some sound files from yakuza kiwami 2.

I use Microsoft Visual Studio to run the exe but before i can even write anything I get this type of error here.

![par extractor error](https://user-images.githubusercontent.com/74937976/100154255-94735500-2ea5-11eb-9b80-f85430e51319.PNG)

What am I doing wrong? How can I start the exe correctly so I can type in the extract command? 
Would really appreciate any help!

**Comment by Kaplas80** [comment]
Hello!

You don't need Visual Studio. Just download the zip with compiled exe from the github releases tab [here](https://github.com/Kaplas80/ParManager/releases/download/v1.3.0/v1.3.0.zip), unzip it and then drag&drop the .par archive on ParTool.exe to extract it.

To create a .par archive, you only need to drag&drop a folder on ParTool.exe.

But if you want to use any other functionality of the app, you have to execute it from a command prompt, double click on the exe is not enough.

All the options and functions are detailed in the [README](https://github.com/Kaplas80/ParManager/blob/develop/README.md) file.
