### ISSUE TITLE
yakuza ishin (original) "bad magic id" 

### ISSUE THREAD

**Issue by JohnYakuzer725** [Kaplas80/ParManager#20]
i tried to extract the heat actions from yakuza ishin but the program just wont let me, keeps giving me this weird error, and it happends with other games too like yakuza kiwami and yakuza 0 
![image](https://github.com/user-attachments/assets/01242a97-1eb2-42cf-b28c-d732431ac030)

**Comment by Kaplas80** [comment]
Hello

The `Bad magic Id` error shows when you try to extract a file that is not a `.par`. What file are you trying to extract?

**Comment by JohnYakuzer725** [comment]
hi, im trying to extract .par files, i double checked all the files im trying to extract and they are in ".par"  format so i dont know what is causing this issue since all of them have the right format

**Comment by Kaplas80** [comment]
I don't have Yakuza Ishin but, if you tell me which files throws the error in Kiwami or Yakuza 0, I can test them.

**Comment by JohnYakuzer725** [comment]
i tried to extract a file called "c_at_kiryu_mou" from kiwami

**Comment by Kaplas80** [comment]
`c_at_kiryu_mou` is a folder, not a file:

![Screenshot_2024-07-25-17-34-51-62_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/user-attachments/assets/49e2bef2-cc03-4d92-af5b-2bd4f9d6e16e)

You should be able to extract `mesh.par` using ParTool

**Comment by JohnYakuzer725** [comment]
tried this 3 times right now, last one the tool decided to extract it, nice but.. still dont know why it does not work with the original yakuza ishin files

**Comment by Timo654** [comment]
ParTool works fine with original Ishin files. Are you sure the files are not encrypted for some reason? I'm not sure which version of Ishin you have, but it's possible that the files are still encrypted if it's not dumped properly.

**Comment by JohnYakuzer725** [comment]
Im using a ps3 yakuza ishin iso. maybe it has some kind of encryption, that could explain why the tool dont work, but then i have to find a way to get rid of that protection...

**Comment by JohnYakuzer725** [comment]
You were right except instead of a bad dump was a bad iso, redumped the game from another iso i found and the tool worked,gosh 2 weeks to discover this im such a fool...
