### ISSUE TITLE
How do I use this library in my project?

### ISSUE THREAD

**Issue by 000Daniel** [Kaplas80/ParManager#6]
'using ParLibrary.Converter;' results in an error "could not be found"

**Comment by Kaplas80** [comment]
Hi!

If you have added the dependencies, it should work. You can see how do I use it in ParTool code, for example for [listing contents](https://github.com/Kaplas80/ParManager/blob/e4f29a47cb3707930143e408c2a524e95b7731e8/ParTool/Program.List.cs)

Keep in mind that the library depends on [Yarhl](https://scenegate.github.io/Yarhl/), so you'll have to include it too.

**Comment by 000Daniel** [comment]
Thanks for the reply!
I got the project to recognize the library but now I have an error,
in ParLibrary/Sllz/Compressor.cs line 115, I get this error:
> cannot convert from 'System.IO.SeekOrigin' to 'Yarhl.IO.SeekMode' [ParLibrary]

How can I fix this?

also another question, how close did you work on RyuModManager?, fyi I'm attempting to compile that project to work with linux

**Comment by Kaplas80** [comment]
The Yarhl API [changed some time ago](https://github.com/SceneGate/Yarhl/pull/161) and I use the newer one in this project, but it is in alpha state, so you can't get it from nuget. You have to follow [the instructions](https://github.com/SceneGate/Yarhl#install) to get the preview release.

And about RyuModManager, I'm not involved with it at all.
