### ISSUE TITLE
Can't open Judgment (PC)'s stream files

### ISSUE THREAD

**Issue by AlpineEscape** [Kaplas80/ParManager#8]
![image](https://user-images.githubusercontent.com/59582518/190858331-f4e0d6e7-25e3-42ab-b039-f693dde11afd.png)

Whenever I try and unpack the streamed audio files (stream.par at 2.5GB and stream_en.par 1.5GB) I get this error.

The tool definitely works though, because I incorrectly extracted sound.par (447MB) first but it pulled all the files out correctly.

What's going on here? I assumed it might be a filesize issue with the tool but it's a different error message to the other open issue about offset addresses.

**Comment by Kaplas80** [comment]
I don't have the game, so I can't test it, but it seems that the .par files in that game are encrypted.

@SutandoTsukai181 have coded a tool to decrypt `chara.par`: https://github.com/SutandoTsukai181/yagami-decryption-agency
and, maybe, he has more info about this

**Comment by mosamadeeb** [comment]
Only `chara.par` and `chara2.par` are encrypted pars, and they can be decrypted with the mentioned tool.

As for `stream.par`, `stmdlc.par` and their `_en` versions... well they are actually CPK files, with `.par` extension:

![image](https://user-images.githubusercontent.com/52977072/190863228-a85fdf34-9f5e-4a04-b8fb-c8ddaa7a6fd8.png)


You can unpack them with a CPK unpacker, someone tried that already and it worked. The files might look encrypted but they can be unpacked just fine.

**Comment by thesoundmind** [comment]
Not sure if this is something to do with ParTool or the decryption, but this was the error I got after running ParTool on the decrypted "chara.par" file. "chara2.par" worked fine, though...! 
![image](https://user-images.githubusercontent.com/114387057/192375395-bb10d5d3-6718-4020-95ab-db9a94028f1a.png)

**Comment by Kaplas80** [comment]
It is a different problem, caused by the file size and an unknown byte value and it is unsolved yet. See issue #7 for more info.
