### ISSUE TITLE
HAct Freeze on YLAD

### ISSUE THREAD

**Issue by Fronkln** [Kaplas80/ParManager#9]
Writing a par with ParLib and using it with a hact on Yakuza 7 will sometimes freeze the game. Likely happens in other games as well
In comparison, Gibbed's Par Utility does not freeze the game with the par its wrote. I have been told it might be because of metadata.

**Comment by Kaplas80** [comment]
How have you created the par file? Using `create` or using `add`?

**Comment by Fronkln** [comment]
Whichever one the drag and drop defaults to

> How have you created the par file? Using `create` or using `add`?

**Comment by Kaplas80** [comment]
I think the problem is in compression. Drag&drop creates the par file using type 1 compression but maybe that file uses type 2 (or no compression at all).

If you upload the original and the new par file to any server, I can look it this weekend.
